use_frameworks!

target 'iOSLetsService_Hero_sdk_Example' do
  
  pod 'Alamofire', '~> 4.7'
  pod 'SwiftyJSON', '~> 4.0'
  pod 'AlamofireObjectMapper', '~> 5.2'
  pod 'AlamofireImage', '~> 3.4'
  pod 'GoogleMaps'
  pod 'GooglePlaces'
  pod 'GooglePlacePicker'

  pod 'iOSLetsService_Hero_sdk', :path => '../'

  target 'iOSLetsService_Hero_sdk_Tests' do
    inherit! :search_paths

    
  end
end
